// Стили верхнего уровня App.jsx: HUD-полоса, разметка страницы (arena/side
// panel), полноэкранные оверлеи (смерть/раунд/баннеры). Стили, принадлежащие
// вынесенным поддкомпонентам (MinibossCompass, ScoreBoard), живут рядом с
// самими компонентами, не здесь — см. frontend/src/components/.
import { colors, panel, fontFamily } from "./ui/theme.js";

export const styles = {
  page: {
    height: "100%",
    width: "100%",
    padding: "12px",
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    fontFamily,
    background: "radial-gradient(circle at 50% 0%, #1e293b 0%, #0f172a 60%, #060a14 100%)",
    userSelect: "none",
    WebkitUserSelect: "none",
  },
  badge: {
    fontSize: "11px",
    letterSpacing: "1.5px",
    color: colors.accent,
    fontWeight: 700,
  },
  h2: { margin: "6px 0 4px", fontSize: "22px", color: colors.text },
  p: { color: colors.textMuted, fontSize: "14px", lineHeight: 1.5 },
  hud: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "24px",
    flexShrink: 0,
    maxWidth: "1400px",
    width: "100%",
    margin: "0 auto 10px",
    padding: "8px 20px",
    boxSizing: "border-box",
    ...panel,
  },
  arenaRow: {
    display: "grid",
    // средняя колонка держит фиксированную (симметричную) ширину под canvas,
    // а боковые — равные "пружины" 1fr: игровое поле остаётся по центру
    // страницы независимо от ширины sidePanel, а не сдвинуто влево от неё
    gridTemplateColumns: "1fr minmax(0, 1400px) 1fr",
    flex: 1,
    minHeight: 0,
    gap: "12px",
  },
  canvasWrap: {
    position: "relative",
    gridColumn: "2",
    minWidth: 0,
    minHeight: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  // боковая колонка вне игрового поля — лидерборд/список игроков/чат больше
  // не лежат поверх арены (перекрывали обзор и мешали целиться/двигаться).
  // Занимает 3-ю grid-колонку, поэтому не влияет на центрирование canvas.
  sidePanel: {
    gridColumn: "3",
    justifySelf: "start",
    width: "260px",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    minHeight: 0,
    overflow: "hidden",
  },
  // границы этого блока точно совпадают с отрендеренным canvas (тот же
  // aspect-ratio + max-width/max-height constraint) — раньше все оверлеи
  // (чат, компас, скорборд) позиционировались от canvasWrap, который часто
  // БОЛЬШЕ самого canvas из-за letterbox-центрирования; из-за этого нижние
  // панели съезжали за пределы видимого игрового поля
  canvasFrame: {
    position: "relative",
    maxWidth: "100%",
    maxHeight: "100%",
  },
  status: { display: "flex", alignItems: "center", gap: "8px", color: colors.text, fontSize: "13px" },
  dot: { width: "8px", height: "8px", borderRadius: "50%", display: "inline-block" },
  hpGroup: { display: "flex", alignItems: "center", gap: "10px" },
  hpBarTrack: {
    width: "120px",
    height: "8px",
    borderRadius: "4px",
    background: "rgba(255,255,255,0.08)",
    overflow: "hidden",
  },
  hpBarFill: { height: "100%", borderRadius: "4px", transition: "width 0.2s ease, background 0.3s ease" },
  hpText: { fontSize: "13px", color: colors.text, minWidth: "50px" },
  statChip: {
    fontSize: "13px",
    color: colors.text,
    background: "rgba(255,255,255,0.06)",
    padding: "2px 8px",
    borderRadius: "6px",
  },
  buffChip: {
    fontSize: "13px",
    fontWeight: 700,
    color: "#052e16",
    background: colors.accent,
    padding: "2px 8px",
    borderRadius: "6px",
  },
  debuffChip: {
    fontSize: "13px",
    fontWeight: 700,
    color: "#fef2f2",
    background: colors.danger,
    padding: "2px 8px",
    borderRadius: "6px",
  },
  weaponChip: {
    fontSize: "13px",
    fontWeight: 700,
    color: "#0f172a",
    background: colors.warning,
    padding: "2px 10px",
    borderRadius: "6px",
  },
  levelChip: {
    fontSize: "13px",
    fontWeight: 700,
    color: "#052e16",
    background: "#4ade80",
    padding: "2px 10px",
    borderRadius: "6px",
  },
  readyChip: {
    color: "#450a0a",
    background: colors.warning,
    fontWeight: 700,
  },
  roundTimer: {
    fontSize: "13px",
    fontWeight: 700,
    color: colors.text,
    background: "rgba(255,255,255,0.06)",
    padding: "2px 10px",
    borderRadius: "6px",
    transition: "background 0.3s ease, color 0.3s ease",
  },
  roundTimerUrgent: {
    color: "#fef2f2",
    background: colors.danger,
  },
};

export const overlayStyles = {
  backdrop: {
    position: "absolute",
    inset: 0,
    background: "rgba(6, 10, 20, 0.6)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    pointerEvents: "none",
    borderRadius: "8px",
  },
  box: {
    padding: "32px 40px",
    textAlign: "center",
    minWidth: "280px",
    pointerEvents: "auto",
    ...panel,
  },
  respawnClassGrid: {
    display: "flex",
    gap: "8px",
    justifyContent: "center",
    marginTop: "16px",
  },
  respawnClassCard: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "4px",
    padding: "8px 10px",
    borderRadius: "8px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.panelBorder,
    background: "rgba(255,255,255,0.03)",
    color: colors.text,
    cursor: "pointer",
    fontFamily,
    fontSize: "16px",
  },
  respawnClassCardActive: {
    borderColor: colors.accent,
    background: colors.accentSoft,
  },
  box2: {
    padding: "48px",
    textAlign: "center",
    maxWidth: "400px",
    margin: "80px auto",
    ...panel,
  },
  statsRow: { display: "flex", gap: "24px", justifyContent: "center", margin: "16px 0 0" },
  stat: { display: "flex", flexDirection: "column", alignItems: "center", gap: "2px" },
  statValue: { fontSize: "22px", fontWeight: 800, color: colors.text },
  statLabel: { fontSize: "11px", color: colors.textMuted, textTransform: "uppercase", letterSpacing: "0.5px" },
  respawnText: { color: colors.textMuted, fontSize: "13px", margin: "16px 0 0" },
  bannerStack: {
    position: "absolute",
    top: "16%",
    left: "50%",
    transform: "translateX(-50%)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "8px",
    pointerEvents: "none",
    zIndex: 10,
  },
  // компактная плашка сверху канваса — не полноэкранный оверлей, не мешает
  // видеть поле, но заметно объявляет победителя раунда
  roundBanner: {
    position: "absolute",
    top: "6%",
    left: "50%",
    transform: "translateX(-50%)",
    padding: "10px 28px",
    borderRadius: "12px",
    textAlign: "center",
    background: "rgba(120, 53, 15, 0.92)",
    border: "2px solid #f59e0b",
    boxShadow: "0 8px 24px rgba(0,0,0,0.45)",
    pointerEvents: "none",
    zIndex: 11,
  },
  roundBannerTitle: {
    fontSize: "12px",
    fontWeight: 700,
    letterSpacing: "1px",
    color: "#fef3c7",
    textTransform: "uppercase",
  },
  roundBannerText: {
    fontSize: "17px",
    fontWeight: 800,
    color: "#fffbeb",
    margin: "2px 0",
  },
  roundBannerSub: {
    fontSize: "11px",
    color: "#fde68a",
  },
  banner: {
    padding: "10px 24px",
    borderRadius: "10px",
    fontSize: "16px",
    fontWeight: 800,
    textAlign: "center",
    whiteSpace: "nowrap",
    boxShadow: "0 8px 24px rgba(0,0,0,0.4)",
    animation: "none",
  },
  banner_danger: {
    background: "rgba(127, 29, 29, 0.92)",
    color: "#fef2f2",
    border: "2px solid #ef4444",
  },
  banner_warning: {
    background: "rgba(120, 53, 15, 0.92)",
    color: "#fef3c7",
    border: "2px solid #f59e0b",
  },
  banner_success: {
    background: "rgba(20, 83, 45, 0.92)",
    color: "#f0fdf4",
    border: "2px solid #22c55e",
  },
};
